name: 🚀 Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🚀 Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: surya
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/surya/surya
            git pull origin main
            docker-compose down
            docker-compose up -d --build
